language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - OUNIT_CI=true
matrix:
  include:
    - name: "ounit: linux"
      os: linux
      env: OCAML_VERSION=4.10 PACKAGE="ounit"

    - name: "ounit-lwt: linux"
      os: linux
      env: OCAML_VERSION=4.10 PACKAGE="ounit-lwt"

    - name: "ounit2: linux"
      apt:
        packages:
          - libxml2-utils
      os: linux
      env: OCAML_VERSION=4.10 PACKAGE="ounit2"

    - name: "ounit2-lwt: linux"
      os: linux
      env: OCAML_VERSION=4.10 PACKAGE="ounit2-lwt"

    - name: "ounit2: reverse dependencies with linux"
      os: linux
      env: OCAML_VERSION=4.10 PACKAGE="ounit2" REVDEPS="mock-ounit junit_ounit pa_ounit qcheck-ounit" POST_INSTALL_HOOK="opam install -t fileutils"

    - name: "ounit2: old ocaml release with linux"
      os: linux
      env: OCAML_VERSION=4.04 PACKAGE="ounit2"

    - name: "ounit: MacOSX"
      os: osx
      env: OCAML_VERSION=4.10 PACKAGE="ounit" REVDEPS="junit_ounit"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

    - name: "ounit2: MacOSX"
      os: osx
      env: OCAML_VERSION=4.10 PACKAGE="ounit2" REVDEPS="junit_ounit"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

    - name: "ounit2-lwt: MacOSX"
      os: osx
      env: OCAML_VERSION=4.10 PACKAGE="ounit2-lwt"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
